### ISSUE TITLE
Segfaults when run under Cygwin

### ISSUE THREAD

**Issue by JoAdams34** [tiny-dnn/tiny-dnn#932]
Hi,
I compiled the code using the latest Cygwin on a Win10 machine.
Both the MNIST and Cifar10 examples fail during training: the former after 4.7 epochs, the latter after 3.2 epochs. The MNIST training example fails silently when compiled in release mode, the Cifar10 example at least outputs an error message:
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted

Compiling the train.cpp files in debug mode with -Og and running them in gdb with
set print thread-events off
run --data_path ../data/

results in this in the case of the MNIST example:

Program received signal ?, Unknown signal.
[Switching to Thread 11596.0x2234]
___chkstk_ms () at ../../../libgcc/config/i386/cygwin.S:146
146     ../../../libgcc/config/i386/cygwin.S: No such file or directory.

(gdb) bt
#0  ___chkstk_ms () at ../../../libgcc/config/i386/cygwin.S:146
#1  0x000000018004637d in vapi_fatal (fmt=0x18021f6b0 <openpty::__PRETTY_FUNCTION__+752> "Can't create per-thread mutex, %E",
    ap=0x6047cbf8 "\003") at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/dcrt0.cc:1285
#2  0x0000000180046422 in api_fatal (fmt=0x18021f6b0 <openpty::__PRETTY_FUNCTION__+752> "Can't create per-thread mutex, %E")
    at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/dcrt0.cc:1305
#3  0x0000000180044292 in init_cygheap::add_tls (this=0x1802fd410, t=0xdc7fce00)
    at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/cygheap.cc:638
#4  0x00000001800455c3 in _cygtls::init_thread (this=<optimized out>, x=<optimized out>, func=<optimized out>)
    at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/cygtls.cc:79
#5  0x00000001800be4ec in pthread_wrapper (arg=arg@entry=0x1803079e0)
    at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/miscfuncs.cc:401
#6  0x000000018004569b in _cygtls::call2 (this=0x6047ce00, func=0x1800be430 <pthread_wrapper(PVOID)>, arg=0x1803079e0,
    buf=buf@entry=0x6047cd50) at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/cygtls.cc:40
#7  0x0000000180045704 in _cygtls::call (func=<optimized out>, arg=<optimized out>)
    at /usr/src/debug/cygwin-2.10.0-1/winsup/cygwin/cygtls.cc:27
#8  0x00007ffcfbd62774 in KERNEL32!BaseThreadInitThunk () from /cygdrive/c/WINDOWS/System32/KERNEL32.DLL
#9  0x00007ffcfc980d51 in ntdll!RtlUserThreadStart () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#10 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

The CIFAR example results in the same issue.

The code was compiled with
-Og -std=gnu++14 -pthread

I assume the root cause is the magic that happens in tiny_dnn/util/aligned_allocator.h
I was unable to compile that header with "-std=c++14". Presumably "posix_memalign" does not work properly with Cygwin?

Thanks,
Jo

**Comment by JoAdams34** [comment]
The problem persists if the code is compiled with either
#define __MINGW32__
or
#define _MSC_VER
although in those cases the gdb backtrace is a bit different:

Program received signal ?, Unknown signal.
0x00007ffcf93c9d98 in RaiseException () from /cygdrive/c/WINDOWS/System32/KERNELBASE.dll
(gdb) bt
#0  0x00007ffcf93c9d98 in RaiseException () from /cygdrive/c/WINDOWS/System32/KERNELBASE.dll
#1  0x000000037154cbc7 in cyggcc_s-seh-1!_Unwind_RaiseException () from /usr/bin/cyggcc_s-seh-1.dll
#2  0x000000037154cca0 in cyggcc_s-seh-1!_Unwind_Resume_or_Rethrow () from /usr/bin/cyggcc_s-seh-1.dll
#3  0x00000003655eb27d in cygstdc++-6!.cxa_rethrow () from /usr/bin/cygstdc++-6.dll
#4  0x000000010045ce64 in std::future<std::result_of<std::decay<tiny_dnn::kernels::fully_connected_op_internal(std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >
#5  0x000000010041d416 in void tiny_dnn::parallel_for<tiny_dnn::kernels::fully_connected_op_internal(std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >
#6  0x0000000100428736 in tiny_dnn::FullyConnectedGradOp::compute(tiny_dnn::core::OpKernelContext&) ()
#7  0x000000010042c23a in tiny_dnn::fully_connected_layer::back_propagation(std::vector<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*, std::allocator<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*> > const&, std::vector<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*, std::allocator<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*> > const&, std::vector<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*, std::allocator<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*> >&, std::vector<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*, std::allocator<std::vector<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> >, std::allocator<std::vector<float, tiny_dnn::aligned_allocator<float, 64ul> > > >*> >&) ()
